import { ReactNode } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/layout/nav'
import styles from '../styles/Home.module.css'

type Props = {
  children?: ReactNode
}

const Home: NextPage = ({ children }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav></Nav>
      <main className={styles.main}>
        <h1>Section</h1>
        {children}
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
